Let try a senario which has more than one label (this case 2)

In [1]:
from sklearn.neighbors import KNeighborsClassifier
import numpy as np

In [2]:
data = [x for x in range(1, 101)]
X_train = np.array(data)
X_train = X_train.reshape(-1, 1) # since knn require 2D input
X_train[:6]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [3]:
y_train_odd = (X_train % 2 == 1).astype(int) # creating label - odd or even class
y_train_large = (X_train >= 50).astype(int) # creating label - large or smaller class
y_multilabel = np.c_[y_train_large, y_train_odd]

In [4]:
# train model 
knn_classifier = KNeighborsClassifier()
knn_classifier.fit(X_train, y_multilabel)

KNeighborsClassifier()

In [5]:
sample_value = np.array([2])
sample_value

array([2])

In [10]:
predict = knn_classifier.predict(sample_value.reshape(-1, 1))
predict

array([[0, 1]])

0, 1 indicate the value (2) is not large and it is even